spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/armandb
    username: arman
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


